format = "${custom.mailbox}$all"

[directory]
truncation_length = 5
truncation_symbol = '…/'

[git_status]
format = '([\[$conflicted$stashed$untracked$modified$staged$renamed$deleted|$ahead_behind\]](bold white) )'
up_to_date = '[✔](bold green)'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
stashed = ''
untracked = '[?${count}](bold cyan)'
modified = '[!${count}](bold blue)'
staged = '[+${count}](bold green)'
renamed = '[»${count}](bold yellow)'
deleted = '[✘${count}](bold red)'

[custom.mailbox]
command = 'export count=$(mailbox view | wc -l) && test $count -gt 0 && echo $count'
when = true
format = '[($output )](bold yellow)'
shell = ['bash', '--noprofile', '--norc']

[custom.port]
command = 'if test -n "$PORTMAN_LINKED_PORT"; then echo "$PORT -> $PORTMAN_LINKED_PORT"; else echo "$PORT"; fi'
when = 'test -n "$PORT"'
format = ':[$output]($style) '
shell = ['bash', '--noprofile', '--norc']
