[schedule.release-watcher]
schedule = "0 0 * * * *" # hourly
command = "release-watcher"

[schedule.homebrew-upgrade]
schedule = "0 0 12 * * *" # every day at noon
command = "fish -c homebrew_upgrade"
makeUpMissedRuns = 1

[schedule.online-backup]
schedule = "0 0 12 * * *" # every day at noon
command = "fish -c backup"
makeUpMissedRuns = 1

[schedule.feed-watcher]
schedule = "0 0 18 * * 6" # every Saturday at 6pm
command = "feed-watcher"
makeUpMissedRuns = 1
