customCommands:
  - key: F
    context: files
    command: git fixup
    output: terminal
  - key: R
    context: files
    command: git recommit
    output: terminal
git:
  paging:
    colorArg: always
    pager: delta --paging=never
gui:
  nerdFontsVersion: "3"
  showIcons: true
os:
  editPreset: vscode
