git:
  paging:
    colorArg: always
    pager: 'delta --paging=never'
gui:
  showIcons: true
os:
  editCommand: code
  editCommandTemplate: '{{editor}} -g {{filename}}:{{line}}'
  openCommand: 'code -rg {{filename}}'
