customCommands:
  - key: F
    context: files
    command: git fixup
    subprocess: true
git:
  paging:
    colorArg: always
    pager: delta --paging=never
gui:
  nerdFontsVersion: '3'
  showIcons: true
os:
  editPreset: vscode
