#!/usr/bin/env bash

cru application secrets read --name mpdx_api --keys HCM_API_USER,HCM_BASE_URL,HCM_ISSUER,HCM_PASSWORD,HCM_PRIVATE_KEY,HCM_USERNAME,HCM_WSDL_URL,HCM_X5T,OKTA_AUTH_CLIENT_IDS,OKTA_ISSUER,OKTA_SERVER_PATH,OKTA_SERVER_URL,SAA_SECRET,SAA_UID
