import $ from "jsr:@david/dax@0.43.2";
import { join } from "jsr:@std/path@1.0.4";
import { TextLineStream } from "jsr:@std/streams@1.0.10";

async function* chain<T>(
  ...iterables: AsyncIterable<T>[]
): AsyncGenerator<T> {
  for (const iterable of iterables) {
    yield* iterable;
  }
}

async function* takeWhile<T>(
  iterable: AsyncIterable<T>,
  predicate: (value: T) => boolean,
): AsyncGenerator<T> {
  for await (const value of iterable) {
    if (!predicate(value)) {
      break;
    }
    yield value;
  }
}

interface GitHubRepo {
  owner: string;
  repo: string;
}
async function getCurrentGitHubRepo(): Promise<GitHubRepo | null> {
  const remoteUrl = await $`git remote get-url origin`.text();
  const match = remoteUrl.match(
    /https:\/\/github\.com\/(?<owner>.+?)\/(?<repo>.+?)(?:\.git)?$/,
  );

  if (!match?.groups) {
    return null;
  }

  const { owner, repo } = match.groups;
  return { owner, repo };
}

const SENTINEL_COMMENT = "# AUTOGENERATED - DO NOT EDIT BELOW THIS LINE";

async function* linesFromFile(filename: string): AsyncGenerator<string> {
  try {
    using file = await Deno.open(filename);
    yield* file.readable
      .pipeThrough(new TextDecoderStream())
      .pipeThrough(new TextLineStream());
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      return;
    }

    throw error;
  }
}

function parseKey(line: string): string | null {
  const trimmed = line.trim();
  if (trimmed.startsWith("#")) {
    return null;
  }

  const splitIndex = trimmed.indexOf("=");
  return splitIndex === -1 ? null : trimmed.slice(0, splitIndex);
}

async function main() {
  const repo = await getCurrentGitHubRepo();
  if (!repo) {
    console.error("No GitHub repository detected");
    Deno.exit(1);
  }

  const homeDir = Deno.env.get("HOME");
  if (!homeDir) {
    console.error("$HOME environment variable is not set");
    Deno.exit(1);
  }

  const envConfigDir = join(
    homeDir,
    ".config",
    "env",
    repo.owner,
    repo.repo,
  );
  const envLocalPath = join(envConfigDir, ".env.local");
  const envSecretsPath = join(envConfigDir, ".env.secrets");

  const envFile = ".env.local";
  const overrideLines = await Array.fromAsync(
    takeWhile(linesFromFile(envFile), (line) => line !== SENTINEL_COMMENT),
  );

  const overrides = new Set<string>();
  for (const line of overrideLines) {
    const key = parseKey(line);
    if (key) {
      overrides.add(key);
    }
  }

  const envLines = [...overrideLines, SENTINEL_COMMENT];
  let envEmpty = true;
  for await (
    const line of chain(
      linesFromFile(envLocalPath),
      linesFromFile(envSecretsPath),
    )
  ) {
    const key = parseKey(line);
    if (key) {
      envLines.push(overrides.has(key) ? `# ${line}` : line);
      envEmpty = false;
    }
  }

  if (envEmpty) {
    console.error(`No env files found for ${repo.owner}/${repo.repo}`);
    Deno.exit(1);
  }

  await Deno.writeTextFile(envFile, envLines.join("\n") + "\n");
  console.log(`Synced environment variables to ${envFile}`);
}

main();
