[tasks.setup]
run = [
  "overcommit --sign",
  "overcommit --install",
  "yarn build:css",
]

[tasks.start]
run = "dev"

[tasks.create-user]
run = "rails runner \"User.create!(username: '', sso_guid: '7d81dc01-3508-4980-829b-7cafb1a334e1', role: 'super_user')\""

[shell_alias]
local-uat = "mise task run local-uat"

[tasks.local-uat]
run = "dotenvx run --env-file .env.local.uat --"
