#!/usr/bin/env bash

commit=$(git reflog | rg 'commit: (?!\w+! )' --pcre2 | fzf --no-sort | cut -w -f1)
if [[ -z "$commit" ]]; then
  exit 1
fi

git log --format=%B --max-count=1 "$commit" | git commit --file=-
