#!/usr/bin/env bash

cru application secrets read --name mpdx_api --keys HCM_BASE_URL,HCM_CLIENT_ID,HCM_CLIENT_SECRET,HCM_OAUTH_SCOPE,HCM_TOKEN_URL,HCM_WSDL_URL,OKTA_AUTH_CLIENT_IDS,OKTA_ISSUER,OKTA_SERVER_PATH,OKTA_SERVER_URL,SAA_SECRET,SAA_UID,SAA_URL
