worktree-path = '''
{% set prefixes = {
  "conf-registration-web": "ert",
  "cru-terraform": "terraform",
  "give-web": "give",
  "mpdx-react": "mpdx",
  "mpdx_api": "mpdx-api",
  "staff_accounting_app": "saa",
} -%}

~/dev/{{ prefixes[remote_repo | default("")] | default(repo) }}-{{ branch | sanitize }}
'''

[list]
json-schema = 2

[[pre-start]]
setup-env = "setup-env --new || true"
portman = "portman create"
dependencies = """
if [ -f yarn.lock ]; then
  yarn
elif [ -f pnpm-lock.yaml ]; then
  pnpm install
elif [ -f package-lock.json ]; then
  npm install
fi
if [ -f Gemfile.lock ]; then
  bundle install
fi
"""

[[post-start]]
open = 'code --profile {{ "Work" if owner | default("") == "CruGlobal" else "Default" }} {{ worktree_path }}'
