#!/usr/bin/env fish

set current_name (git rev-parse --abbrev-ref HEAD)
set new_name "$current_name-backup"
set suffix 2

while git show-ref --quiet refs/heads/$new_name
    set new_name "$current_name-backup$suffix"
    set suffix (math $suffix + 1)
end

git branch $new_name
echo "Backed up the current branch to $new_name"
