#!/usr/bin/env bash

current_name=$(git rev-parse --abbrev-ref HEAD)
new_name="$current_name-backup"
suffix=2

while git show-ref --quiet "refs/heads/$new_name"; do
  new_name="$current_name-backup$suffix"
  ((suffix++))
done

git branch "$new_name"
echo "Backed up the current branch to $new_name"
