#!/usr/bin/env fish

set file $argv[1]

if test -z $file
    # No file was provided, so choose one interactively
    set file (fd --type file | fzf --ghost "Choose a file to trace its history" || return 1)
end

set commit (git l "$file" | fzf --preview "git -c color.ui=always sw {1} \"$file\"" --preview-window 'right,75%' --accept-nth 1 || return 1)
git show $commit -- $file
