#!/usr/bin/env fish

set current_branch $(git current)
if test -z $current_branch
    echo "Error: You are not currently on a branch"
    exit 1
end

# Check for argument
if test (count $argv) -lt 1
    echo "Usage: git merge-into <target-branch>"
    exit 1
end

set target_branch $argv[1]

git switch $target_branch &&
    git pull &&
    git merge $current_branch --no-edit &&
    git push &&
    git switch $current_branch
