#!/usr/bin/env fish

if test (count $argv) -lt 1
    echo "Usage: git merge-into <target-branch>"
    exit 1
end

git switch $argv[1]
and git pull
and git merge - --no-edit
and git push
and git switch -
